---
title: "linear_models"
author: "yz5248"
date: "2025-11-06"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    stars = review_scores_location / 2
  ) |> 
  rename(
    borough = neighbourhood_group,
    ) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighbourhood, room_type)

nyc_airbnb
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
fit
```

```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)
summary(fit)
```

```{r}
fit |> 
  broom::glance()
```

```{r}
fit |> 
  broom::tidy()
```

```{r}
fit |> 
  broom::tidy() |> 
  select(term, estimate, p.value) |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  knitr::kable(digits = 3)
```

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  modelr::add_predictions(fit) |>
  filter(resid < 1000) |>
  ggplot(aes(x = stars, y = resid)) +
  geom_point()
```

```{r}
nyc_airbnb |>
  modelr::add_residuals(fit) |>
  modelr::add_predictions(fit) |>
  filter(resid < 1000) |>
  ggplot(aes(x = borough, y = resid)) +
  geom_point()
```

what about categorical variable
```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

anova(fit_null, fit_alt) |>
  broom::tidy()
```

```{r}
fit_interactions =
  lm(price ~ stars * borough + room_type * borough, data = nyc_airbnb)

fit_interactions |>  
  broom::tidy() |> 
  knitr::kable(digits = 3)
```


let's just focus on brooklyn
```{r}
nyc_airbnb |>
  filter(borough == "Brooklyn") |>
  lm(price ~ stars + room_type, data = _) |>
  broom::tidy()
```

```{r}
lm_airbnb = function(df) {
  lm(price ~ stars + room_type, data = df)
}

nyc_airbnb |>
  filter(borough == "Queens") |>
  lm_airbnb() |>
  broom::tidy()
```


create a list of dataframes, and iterate to fit 
```{r}
nested_lm_results =
nyc_airbnb |>
  nest(data = -borough) |>
  mutate(
    fits = map(data, lm_airbnb),
    results = map(fits, broom::tidy)
  ) |>
  select(borough, results) |>
  unnest(results)
```

do some untidying
```{r}
nested_lm_results |>
  select(borough, term, estimate) |>
  pivot_wider(
    names_from = term,
    values_from = estimate
  )
```

usa an "anonymous" function
```{r}
nested_lm_results =
  nyc_airbnb |>
  nest(data = -borough) |>
  mutate(
    fits = map(data, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(fits, broom::tidy)
  ) |>
  select(borough, results) |>
  unnest(results)

nested_lm_results |>
  select(borough, term, estimate) |>
  pivot_wider(
    names_from = term,
    values_from = estimate
  )
```

more example
```{r}
manhattan_analysis = 
  nyc_airbnb |>
  filter(
    borough == "Manhattan"
  ) |>
  nest(data = -neighbourhood) |>
  mutate(
    fits = map(data, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(fits, broom::tidy)
  ) |>
  select(neighbourhood, results) |>
  unnest(results)
```

```{r}
manhattan_analysis |>
  filter(term == "stars") |>
  mutate(
    neighbourhood = fct_reorder(neighbourhood, estimate)
  ) |>
  ggplot(aes(x = neighbourhood, y = estimate)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

